apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: plane-project
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/vladoz77/plane-cd.git
  - https://helm.plane.so/
  destinations:
  - namespace: plane
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
