apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: plane
spec:
  project: plane-project
  sources:
  - repoURL: https://helm.plane.so/
    chart: makeplane
    targetRevision: "1.1.1"
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: plane
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
