apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
  labels:
    app: plane
spec:
  project: plane-project
  sources:
  - repoURL: https://github.com/vladoz77/plane-cd.git
    targetRevision: HEAD
    ref: myRepo
  - repoURL: https://helm.plane.so/
    chart: plane-ce
    targetRevision: 1.1.1
    helm:
      valueFiles:
      - $myRepo/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: plane
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
